### ISSUE TITLE
error processing package grub-pc

### ISSUE THREAD

**Issue by lxl66566** [lxl66566/init-script#1]
系统：debian12

在 install ALL 刚开始没多久时（执行语句：apt upgrade）出现错误：

```
Setting up openssh-server (1:9.2p1-2+deb12u2) ...
Creating SSH2 ECDSA key; this may take some time ...
256 SHA256:bzOgfaJSJFls0B3gErZPXd4QByFcmzkoPSdthn8cJgQ root@ABSOLUTEX (ECDSA)
Creating SSH2 ED25519 key; this may take some time ...
256 SHA256:PwrHuskWqCRFNk3M4JUtWcWISA7S9CIbtfoKOPK+u/w root@ABSOLUTEX (ED25519)
rescue-ssh.target is a disabled or a static unit not running, not starting it.
ssh.socket is a disabled or a static unit not running, not starting it.
Setting up bind9-dnsutils (1:9.18.24-1) ...
Setting up ssh (1:9.2p1-2+deb12u2) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for initramfs-tools (0.142) ...
update-initramfs: Generating /boot/initrd.img-6.1.0-21-amd64
Processing triggers for libc-bin (2.36-9+deb12u7) ...
Errors were encountered while processing:
grub-pc
E: Sub-process /usr/bin/dpkg returned an error code (1)
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/absx/init-script/init-script/__main__.py", line 63, in <module>
install_init()
File "/absx/init-script/init-script/install/__init__.py", line 134, in init
rc_sudo("DEBIAN_FRONTEND=noninteractive apt upgrade -y")
File "/absx/init-script/init-script/utils/__init__.py", line 42, in rc_sudo
return rc(s, **kwargs)
^^^^^^^^^^^^^^^
File "/absx/init-script/init-script/utils/__init__.py", line 33, in rc
return subprocess.run(s, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/subprocess.py", line 571, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'DEBIAN_FRONTEND=noninteractive apt upgrade -y' returned non-zero exit status 100.
```

**Comment by lxl66566** [comment]
1. 根据报错信息，执行 `DEBIAN_FRONTEND=dialog dpkg --configure grub-pc && dpkg --configure -a`
2. 在弹出面板中，选择所有磁盘即可。（空格选中；回车确认）
